services:
  finance_backend:
    image: ${DOCKER_REGISTRY-}financebackend
    build:
      context: .
      dockerfile: FinanceBackend/Dockerfile
    ports:
      - "8080:8080" 
    container_name: finance_backend_app
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_DB: finance_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: finance_backend_db
volumes:
  db_data:
